language: python
sudo: false

python:
  - '2.6'
  - '2.7'
  - '3.4'

env:
  - DJANGO_VERSION=1.9.x
  - DJANGO_VERSION=1.8.x
  - DJANGO_VERSION=1.7.x
  - DJANGO_VERSION=1.6.x

matrix:
  exclude:
  - python: '2.6'
    env: DJANGO_VERSION=1.7.x
  - python: '2.6'
    env: DJANGO_VERSION=1.8.x
  - python: '2.6'
    env: DJANGO_VERSION=1.9.x

install:
  - pip install tox

script:
  - tox -e "$TRAVIS_PYTHON_VERSION-$DJANGO_VERSION"

after_success:
  - pip install "coveralls==1.1" coverage
  - coverage report
  - coveralls

services:
  - redis-server
